name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: '3.8.1'

      - name: Build with Maven
        run: mvn package
