name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  CI-CD:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven

      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: '3.8.1'

      - name: Cache the maven packages to speed up the build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2


      - name: Build with Maven
        run: mvn package

      - name: Deploy
        run: java -jar target/springbootmongodb-0.0.1-SNAPSHOT.jar
